// Generated by CoffeeScript 1.6.2
/*
# API Wireup
*/


(function() {
  var haikus;

  exports.haikus = haikus = require('./api.haikus');

  exports.notAllowed = function(req, res) {
    return res.send(405);
  };

  exports.index = function(req, res) {
    return res.sendfile('public/index.html');
  };

  exports.configure = function(app) {
    app.get('/haikus/random', haikus.getRandom);
    app.get('/haikus/:id', haikus.getSingle);
    app.get('/haikus/:id/like', haikus.likeSingle);
    app.post('/haikus/:id', exports.notAllowed);
    app.put('/haikus/:id', exports.notAllowed);
    app["delete"]('/haikus/:id', haikus.deleteSingle);
    app.get('/haikus', haikus.get);
    app.post('/haikus', haikus.post);
    app.put('/haikus', exports.notAllowed);
    app["delete"]('/haikus', exports.notAllowed);
    return app.get('*', exports.index);
  };

}).call(this);
